language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
env:
  global:
  - IMAGE=fschutte/cerioscoop
  - COMMIT=${TRAVIS_COMMIT::8}
  - IMAGE_VERSION=$IMAGE:travis-$TRAVIS_BUILD_NUMBER
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_INSTALL_DIR=googlestuff
# de CLOUDSDK_CORE_DISABLE_PROMPTS is nodig want anders gaat travis wachten op input en geeft het een timeout
# de CLOUDSDK_INSTALL_DIR is nodig want anders neemt hij default dir google-cloud-sdk en die bestaat al
cache:
  directories:
  - $HOME/$CLOUDSDK_INSTALL_DIR

before_install:
- openssl aes-256-cbc -K $encrypted_418a88f24735_key -iv $encrypted_418a88f24735_iv
  -in client-secret.json.enc -out client-secret.json -d
- chmod +x publish-codacy-coverage
script:
- mvn package jacoco:report
after_success:
- ./publish-codacy-coverage
- echo $IMAGE_VERSION
- docker build -t $IMAGE_VERSION .
- docker tag $IMAGE_VERSION $IMAGE:latest
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker push $IMAGE
# travis komt met een verouderde gcloud versie en we hebben een nieuwe nodig
# want anders kunnen we kubectl niet installeren
- gcloud version
- curl https://sdk.cloud.google.com | bash
- source /home/travis/.bashrc
- gcloud version
- gcloud components install kubectl
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud components update kubectl
- gcloud config set compute/zone europe-west1-b
- gcloud config set core/project cerioscoop-project
- gcloud container clusters get-credentials cerioscoop-cluster
# met het patch commando kunnen we de image in een deployment updaten
- kubectl patch deployment cerioscoop-deployment -p   '{"spec":{"template":{"spec":{"containers":[{"name":"cerioscoop-deployment","image":"'"$IMAGE_VERSION"'"}]}}}}'
