language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker
  
env:
  global:
    - IMAGE=fschutte/cerioscoop
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE_VERSION=$IMAGE:$COMMIT
  
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  
before_install:
  - chmod +x publish-codacy-coverage

script:
  - mvn package jacoco:report

after_success: 
- ./publish-codacy-coverage
- echo $IMAGE:$COMMIT
- openssl aes-256-cbc -K $encrypted_418a88f24735_key -iv $encrypted_418a88f24735_iv
  -in client-secret.json.enc -out client-secret.json -d
- docker build -t $IMAGE:$COMMIT .
- docker tag $IMAGE:$COMMIT $IMAGE:latest
- docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker push $IMAGE
- gcloud version
- travis_wait curl https://sdk.cloud.google.com | bash
- echo "klaar met gcloud installeren"
- source /home/travis/.bashrc
- gcloud version
- bash -l ./gcloud.sh version
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud components update kubectl
- gcloud config set core/project cerioscoop-project
# - kubectl run hello-cerioscoop --image=$DOCKER_IMAGE_NAME:latest --port=80
# we gaan uit van een al draaiende omgeving en hoeven dan alleen een patch te doen
- kubectl patch deployment cerioscoop-deployment -p   '{"spec":{"template":{"spec":{"containers":[{"name":"cerioscoop-deployment","image":"'"$IMAGE_VERSION"'"}]}}}}'
