language: java
jdk:
- oraclejdk8
sudo: required

services:
  - docker
  
env:
  - IMAGE=fschutte/cerioscoop
  - COMMIT=${TRAVIS_COMMIT::8}
  - IMAGE_VERSION=$IMAGE:$COMMIT
  
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  
before_install:
- chmod +x publish-codacy-coverage
script:
- mvn package jacoco:report
env: 
after_success: 
- ./publish-codacy-coverage
- docker build -t $IMAGE:$COMMIT .
- docker tag $IMAGE:$COMMIT $IMAGE:latest
- docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker push $IMAGE
- curl https://sdk.cloud.google.com | bash
- source /home/travis/.bashrc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file $GCLOUD_KEYFILE
- gcloud components update kubectl
- gcloud config set core/project cerioscoop-project
# - kubectl run hello-cerioscoop --image=$DOCKER_IMAGE_NAME:latest --port=80
# we gaan uit van een al draaiende omgeving en hoeven dan alleen een patch te doen
- kubectl patch deployment cerioscoop-deployment -p   '{"spec":{"template":{"spec":{"containers":[{"name":"cerioscoop-deployment","image":"'"$IMAGE_VERSION"'"}]}}}}'
